/**
 * ShareNet 2.0 — R-002B: Link Authentication Attack Suite.
 *
 * Per R-002B requirement: 7 mandatory negative tests proving each attack
 * fails closed. The proof statement each signature must make:
 *
 *   "The holder of NodeId X's private key participated in this specific
 *    transport handshake, with these exact roles, identities, and
 *    transcript bytes."
 *
 * If the signature proves less than that, it is not link authentication.
 *
 * Attacks tested:
 *   1. Replay: capture handshake, reuse later
 *   2. Advertisement substitution: swap advertisement during handshake
 *   3. NodeId swap: public key belongs to A, NodeId claims B
 *   4. Role swap: initiator transcript used as responder proof
 *   5. Transcript substitution: valid proof for transcript X on transcript Y
 *   6. Challenge reuse: same challenge across sessions
 *   7. Endpoint substitution: advertised endpoint ≠ authenticated endpoint
 *
 * Plus: R-002A state machine enforcement (no bypass path).
 */

import { describe, test, expect } from "bun:test";
import {
  generateNodeKeypair,
  randomBytes,
  bytesToHex,
  hexToBytes,
} from "@reference/identity/keys";
import {
  signAdvertisement,
  verifyAdvertisement,
  advertisementToHex,
  type NodeCapability,
} from "@reference/advertisement/advertisement";
import {
  computeTranscriptHash,
  computeLinkIdBytes,
  signPossessionProof,
  verifyPossessionProof,
  encodeInitiate,
  encodeAccept,
  encodeConfirm,
  decodeMessage,
  POSSESSION_DOMAIN_INITIATOR,
  POSSESSION_DOMAIN_RESPONDER,
  ROLE_INITIATOR,
  ROLE_RESPONDER,
  MSG_KIND,
  ChallengeCache,
  type InitiateMessage,
  type AcceptMessage,
  type ConfirmMessage,
} from "@reference/transport/auth-handshake";
import {
  LinkAuthStateMachine,
  ADV_TO_LINK_UP_FORBIDDEN,
  HINT_TO_LINK_UP_FORBIDDEN,
  SKIP_HANDSHAKE_FORBIDDEN,
} from "@reference/transport/link-auth-state";
import { createRemoteNodeHint } from "@reference/topology/remote-node-hint";

const REFERENCE_NOW = 1786876545;

function setupHandshake() {
  const kpA = generateNodeKeypair();
  const kpB = generateNodeKeypair();
  const caps: NodeCapability[] = ["MESH_RELAY"];

  const advA = signAdvertisement({
    protocolVersion: 1, nodeId: kpA.nodeId, signingPublicKey: kpA.publicKey,
    capabilities: caps, endpoints: [{ type: "tcp", address: "10.0.0.1", port: 7788 }],
    sequence: 1, timestamp: REFERENCE_NOW, expiry: REFERENCE_NOW + 3600,
    nonce: randomBytes(16),
  }, kpA.secretKey);

  const advB = signAdvertisement({
    protocolVersion: 1, nodeId: kpB.nodeId, signingPublicKey: kpB.publicKey,
    capabilities: caps, endpoints: [{ type: "tcp", address: "10.0.0.2", port: 7789 }],
    sequence: 1, timestamp: REFERENCE_NOW, expiry: REFERENCE_NOW + 3600,
    nonce: randomBytes(16),
  }, kpB.secretKey);

  const linkNonceA = randomBytes(16);
  const linkNonceB = randomBytes(16);
  const challengeForB = randomBytes(32);
  const challengeForA = randomBytes(32);

  // Build Initiate
  const initiate: InitiateMessage = {
    kind: MSG_KIND.INITIATE,
    advertisementHex: bytesToHex(encodeInitiate({
      kind: MSG_KIND.INITIATE,
      advertisementHex: "", // placeholder, will set below
      linkNonceA, challengeForB,
    })), // we'll use the actual encode below
    linkNonceA, challengeForB,
  };
  // Actually encode properly
  const advAHex = bytesToHex(encodeInitiate({
    kind: MSG_KIND.INITIATE as number,
    advertisementHex: "", // not used this way
    linkNonceA, challengeForB,
  } as any));

  // Let me do this properly
  const initiateMsg: InitiateMessage = {
    kind: MSG_KIND.INITIATE,
    advertisementHex: advAHex || "", // we need the advertisement hex
    linkNonceA,
    challengeForB,
  };

  // Actually, the InitiateMessage carries advertisementHex which is the hex
  // of the signed advertisement CBOR. Let me use advertisementToHex.
  const advAHexReal = advertisementToHex(advA);
  const advBHexReal = advertisementToHex(advB);

  const initiateReal: InitiateMessage = {
    kind: MSG_KIND.INITIATE,
    advertisementHex: advAHexReal,
    linkNonceA,
    challengeForB,
  };
  const initiateBytes = encodeInitiate(initiateReal);

  // Compute LinkId (responder perspective: local=B, remote=A)
  const linkIdBytes = computeLinkIdBytes(kpB.nodeId, kpA.nodeId, linkNonceB, linkNonceA);

  // Transcript hash after Initiate
  const transcriptAfterInitiate = computeTranscriptHash([initiateBytes]);

  // B signs challengeForB (generated by A), with RESPONDER role
  const proofB = signPossessionProof(
    kpB.secretKey, POSSESSION_DOMAIN_RESPONDER,
    transcriptAfterInitiate, linkIdBytes, challengeForB, ROLE_RESPONDER,
  );

  const acceptMsg: AcceptMessage = {
    kind: MSG_KIND.ACCEPT,
    advertisementHex: advBHexReal,
    linkNonceB, challengeForA, proofB,
  };
  const acceptBytes = encodeAccept(acceptMsg);

  // Transcript hash after Initiate + Accept
  const transcriptAfterAccept = computeTranscriptHash([initiateBytes, acceptBytes]);

  // A signs challengeForA (generated by B), with INITIATOR role
  const proofA = signPossessionProof(
    kpA.secretKey, POSSESSION_DOMAIN_INITIATOR,
    transcriptAfterAccept, linkIdBytes, challengeForA, ROLE_INITIATOR,
  );

  const confirmMsg: ConfirmMessage = { kind: MSG_KIND.CONFIRM, proofA };
  const confirmBytes = encodeConfirm(confirmMsg);

  return {
    kpA, kpB, advA, advB, advAHexReal, advBHexReal,
    linkNonceA, linkNonceB, challengeForB, challengeForA,
    initiateBytes, acceptBytes, confirmBytes,
    linkIdBytes, transcriptAfterInitiate, transcriptAfterAccept,
    proofB, proofA,
  };
}

describe("R-002A: Link authentication state machine enforcement", () => {
  test("LINK_UP requires full pipeline: AD_VERIFIED → CHALLENGE → PROOF → TRANSCRIPT → LINK_UP", () => {
    const sm = new LinkAuthStateMachine();
    expect(sm.getState()).toBe("AD_CREATED");

    // Cannot skip to LINK_UP from AD_CREATED
    expect(sm.transition("LINK_UP", "bypass attempt")).toBe(false);
    expect(sm.getState()).toBe("AD_CREATED");

    // Valid path
    expect(sm.transition("AD_VERIFIED", "advertisement verified")).toBe(true);
    expect(sm.transition("HANDSHAKE_CHALLENGE", "challenge issued")).toBe(true);
    expect(sm.transition("PROOF_OF_POSSESSION", "proof received")).toBe(true);
    expect(sm.transition("TRANSCRIPT_VERIFIED", "transcript verified")).toBe(true);
    expect(sm.transition("LINK_UP", "fully authenticated")).toBe(true);
    expect(sm.isLinkUp()).toBe(true);
  });

  test("ADV_TO_LINK_UP_FORBIDDEN throws", () => {
    const kp = generateNodeKeypair();
    const adv = signAdvertisement({
      protocolVersion: 1, nodeId: kp.nodeId, signingPublicKey: kp.publicKey,
      capabilities: ["MESH_RELAY"], endpoints: [],
      sequence: 1, timestamp: REFERENCE_NOW, expiry: REFERENCE_NOW + 3600,
      nonce: randomBytes(16),
    }, kp.secretKey);
    expect(() => ADV_TO_LINK_UP_FORBIDDEN(adv)).toThrow();
  });

  test("HINT_TO_LINK_UP_FORBIDDEN throws", () => {
    const reporter = generateNodeKeypair();
    const subject = generateNodeKeypair();
    const hint = createRemoteNodeHint({
      reporterNodeId: reporter.nodeId, subjectNodeId: subject.nodeId,
      subjectEndpointHint: "10.0.0.5:7788", claimedCapabilities: ["MESH_RELAY"],
      hopCount: 0, timestamp: REFERENCE_NOW, nonce: randomBytes(16),
    }, reporter.secretKey);
    expect(() => HINT_TO_LINK_UP_FORBIDDEN(hint)).toThrow();
  });

  test("SKIP_HANDSHAKE_FORBIDDEN throws", () => {
    expect(() => SKIP_HANDSHAKE_FORBIDDEN("AD_VERIFIED", "LINK_UP")).toThrow();
  });

  test("ADV_VERIFIED is NOT routable (isLinkUp = false)", () => {
    const sm = new LinkAuthStateMachine();
    sm.transition("AD_VERIFIED", "verified");
    expect(sm.isLinkUp()).toBe(false);
    expect(sm.isAdvVerifiedOnly()).toBe(true);
  });
});

describe("R-002B: Link authentication attack suite", () => {
  // --- 1. Replay: capture handshake, reuse later ---
  test("ATTACK 1 — Replay: old proof on new transcript FAILS", () => {
    const ctx = setupHandshake();

    // Attacker captures the old Accept message (with old proofB)
    // and replays it in a NEW connection with a different transcript.
    // The new connection has different linkNonceA → different transcript.
    const fakeNonceA = randomBytes(16);
    const fakeInitiate: InitiateMessage = {
      kind: MSG_KIND.INITIATE,
      advertisementHex: ctx.advAHexReal,
      linkNonceA: fakeNonceA, // different nonce
      challengeForB: ctx.challengeForB,
    };
    const fakeInitiateBytes = encodeInitiate(fakeInitiate);
    const fakeTranscript = computeTranscriptHash([fakeInitiateBytes]);

    // The old proofB was signed over the OLD transcript, not the fake one
    const proofBOk = verifyPossessionProof(
      ctx.kpB.publicKey, ctx.proofB,
      POSSESSION_DOMAIN_RESPONDER,
      fakeTranscript, // WRONG transcript
      ctx.linkIdBytes, ctx.challengeForB, ROLE_RESPONDER,
    );
    expect(proofBOk).toBe(false); // MUST fail
  });

  // --- 2. Advertisement substitution: swap advertisement during handshake ---
  test("ATTACK 2 — Advertisement substitution: swap advA with advC FAILS", () => {
    const ctx = setupHandshake();
    const kpC = generateNodeKeypair();
    const advC = signAdvertisement({
      protocolVersion: 1, nodeId: kpC.nodeId, signingPublicKey: kpC.publicKey,
      capabilities: ["MESH_RELAY"], endpoints: [],
      sequence: 1, timestamp: REFERENCE_NOW, expiry: REFERENCE_NOW + 3600,
      nonce: randomBytes(16),
    }, kpC.secretKey);
    const advCHex = advertisementToHex(advC);

    // Attacker replaces A's advertisement with C's in the Initiate message
    const tamperedInitiate: InitiateMessage = {
      kind: MSG_KIND.INITIATE,
      advertisementHex: advCHex, // WRONG advertisement
      linkNonceA: ctx.linkNonceA,
      challengeForB: ctx.challengeForB,
    };
    const tamperedBytes = encodeInitiate(tamperedInitiate);
    const tamperedTranscript = computeTranscriptHash([tamperedBytes]);

    // The proofB was signed over the ORIGINAL transcript (with A's advertisement)
    const proofBOk = verifyPossessionProof(
      ctx.kpB.publicKey, ctx.proofB,
      POSSESSION_DOMAIN_RESPONDER,
      tamperedTranscript, // different because adv changed
      ctx.linkIdBytes, ctx.challengeForB, ROLE_RESPONDER,
    );
    expect(proofBOk).toBe(false); // MUST fail — transcript changed
  });

  // --- 3. NodeId swap: public key belongs to A, NodeId claims B ---
  test("ATTACK 3 — NodeId swap: key A with NodeId B FAILS", () => {
    const kpA = generateNodeKeypair();
    const kpB = generateNodeKeypair();

    // Sign an advertisement with A's key but claim B's NodeId
    const adv = signAdvertisement({
      protocolVersion: 1,
      nodeId: kpA.nodeId, // correct
      signingPublicKey: kpA.publicKey,
      capabilities: ["MESH_RELAY"], endpoints: [],
      sequence: 1, timestamp: REFERENCE_NOW, expiry: REFERENCE_NOW + 3600,
      nonce: randomBytes(16),
    }, kpA.secretKey);

    // Tamper: claim B's NodeId
    const tampered = { ...adv, nodeId: kpB.nodeId };
    const v = verifyAdvertisement(tampered, REFERENCE_NOW);
    expect(v.ok).toBe(false);
    if (!v.ok) expect(v.error).toBe("IDENTITY_BINDING_MISMATCH");
  });

  // --- 4. Role swap: initiator transcript used as responder proof ---
  test("ATTACK 4 — Role swap: initiator proof with responder domain FAILS", () => {
    const ctx = setupHandshake();

    // Try to verify proofA (signed with INITIATOR domain) using RESPONDER domain
    const proofAOk = verifyPossessionProof(
      ctx.kpA.publicKey, ctx.proofA,
      POSSESSION_DOMAIN_RESPONDER, // WRONG domain
      ctx.transcriptAfterAccept, ctx.linkIdBytes, ctx.challengeForA, ROLE_INITIATOR,
    );
    expect(proofAOk).toBe(false); // MUST fail — wrong domain tag

    // Try to verify proofB (signed with RESPONDER domain) using INITIATOR domain
    const proofBOk = verifyPossessionProof(
      ctx.kpB.publicKey, ctx.proofB,
      POSSESSION_DOMAIN_INITIATOR, // WRONG domain
      ctx.transcriptAfterInitiate, ctx.linkIdBytes, ctx.challengeForB, ROLE_RESPONDER,
    );
    expect(proofBOk).toBe(false); // MUST fail
  });

  // --- 5. Transcript substitution: valid proof for X on transcript Y ---
  test("ATTACK 5 — Transcript substitution: proof from session X on session Y FAILS", () => {
    const ctx1 = setupHandshake();
    const ctx2 = setupHandshake();

    // Use ctx1's proofB with ctx2's transcript
    const proofBOk = verifyPossessionProof(
      ctx1.kpB.publicKey, ctx1.proofB,
      POSSESSION_DOMAIN_RESPONDER,
      ctx2.transcriptAfterInitiate, // WRONG transcript (from different session)
      ctx2.linkIdBytes, // also different (different nonces)
      ctx1.challengeForB, ROLE_RESPONDER,
    );
    expect(proofBOk).toBe(false); // MUST fail
  });

  // --- 6. Challenge reuse: same challenge across sessions ---
  test("ATTACK 6 — Challenge reuse: same challenge in two sessions rejected by freshness", () => {
    const challenge = randomBytes(32);
    const cache = new ChallengeCache();

    // First session: challenge is registered and consumed
    cache.registerChallenge(challenge);
    const r1 = cache.consumeChallenge(challenge);
    expect(r1.ok).toBe(true);

    // Second session: same challenge is replayed
    const r2 = cache.consumeChallenge(challenge);
    expect(r2.ok).toBe(false);
    if (!r2.ok) expect(r2.reason).toContain("replay");
  });

  // --- 7. Endpoint substitution: advertised endpoint ≠ authenticated endpoint ---
  test("ATTACK 7 — Endpoint substitution: different endpoint in advertisement FAILS identity binding", () => {
    const ctx = setupHandshake();

    // The advertisement carries the endpoint. If an attacker changes the
    // endpoint in the advertisement, the advertisement signature becomes invalid
    // (the signature covers the canonical CBOR which includes the endpoint).
    const tamperedAdv = { ...ctx.advA, endpoints: [{ type: "tcp" as const, address: "evil.com", port: 9999 }] };
    const v = verifyAdvertisement(tamperedAdv, REFERENCE_NOW);
    expect(v.ok).toBe(false); // MUST fail — signature covers the endpoint
    if (!v.ok) expect(v.error).toBe("INVALID_SIGNATURE");
  });
});
