/**
 * ShareNet 2.0 — R-002-P1: AuthenticatedLink proof artifact.
 *
 * Per the R-002-P1 directive (Principal Architect refinement):
 *
 *   "R-002-P1 should introduce the runtime AuthenticatedLink proof
 *    artifact, and ValidatedHop should consume it. That single change
 *    would simultaneously strengthen R-002 and make the R-006 trust
 *    chain semantically complete."
 *
 * The previous trust chain had a gap:
 *
 *   AuthenticatedNodeRecord + caller-supplied linkUp:boolean
 *       ↓
 *   ValidatedHop
 *
 * A caller holding a genuine AuthenticatedNodeRecord could do:
 *   createValidatedHop(authenticNode, endpoint, capability, true, arbitraryDigest)
 * with NO proof that the directed link actually completed the
 * authenticated handshake.
 *
 * The target trust chain is:
 *
 *   VerifiedNodeAdvertisement (WeakSet)
 *       ↓
 *   AuthenticatedNodeRecord (WeakSet)
 *       ↓
 *   VerifiedTranscript (WeakSet)        — both possession proofs verified
 *       ↓
 *   AuthenticatedLink (WeakSet)         — binds the transcript to the node
 *       ↓
 *   ValidatedHop (WeakSet)              — consumes the genuine link
 *
 * A VerifiedTranscript is the cryptographic evidence that a 3-message
 * handshake completed (per ADR-0016 RESOLVED): both parties signed the
 * transcript with their Ed25519 keys, each signing the PEER-generated
 * challenge, bound to the directional LinkId and the transcript hash.
 *
 * An AuthenticatedLink binds a VerifiedTranscript to an
 * AuthenticatedNodeRecord: "this authenticated node participated in
 * this specific verified handshake, on this specific directed link."
 *
 * ValidatedHop now consumes an AuthenticatedLink (not a boolean) —
 * linkUp is no longer caller-supplied trust; it is implied by the
 * genuine link artifact.
 */

import { toHex } from "../encoding/cbor";
import {
  verifyPossessionProof,
  computeTranscriptHash,
  POSSESSION_DOMAIN_INITIATOR,
  POSSESSION_DOMAIN_RESPONDER,
  ROLE_INITIATOR,
  ROLE_RESPONDER,
} from "./auth-handshake";
import type { AuthenticatedNodeRecord } from "./validated-types";
import { isAuthenticatedNodeRecord } from "./validated-types";

// -----------------------------------------------------------------------
// Private WeakSet registries (genuinely unforgeable)
// -----------------------------------------------------------------------

const verifiedTranscriptRegistry = new WeakSet<object>();
const authenticatedLinkRegistry = new WeakSet<object>();

// -----------------------------------------------------------------------
// VerifiedTranscript — both possession proofs verified
// -----------------------------------------------------------------------

/**
 * A VerifiedTranscript is the proof that a 3-message handshake completed.
 *
 * Per ADR-0016 RESOLVED: both parties signed the transcript:
 *   - The responder (B) signs the challenge generated by A, with role RESPONDER,
 *     over the transcript hash of the Initiate message (B has only seen
 *     message_1 when it signs — it knows message_2 because B creates it,
 *     but the canonical transcript state at signing time is hash(Initiate)).
 *   - The initiator (A) signs the challenge generated by B, with role INITIATOR,
 *     over the transcript hash of Initiate + Accept (A has seen both).
 *
 * createVerifiedTranscript() verifies BOTH proofs before registering.
 * If either proof fails, no artifact is produced.
 */
export interface VerifiedTranscript {
  /** The final transcript digest = hash(Initiate, Accept) — used as the canonical binding. */
  readonly transcriptDigestHex: string;
  readonly linkIdHex: string;
  readonly linkIdBytes: Uint8Array;
  readonly initiatorNodeId: string;
  readonly responderNodeId: string;
  readonly verifiedAt: number;
}

/**
 * The ONLY function that creates a VerifiedTranscript.
 *
 * Takes the raw wire bytes of the Initiate and Accept messages and
 * computes the two transcript hashes internally:
 *   - responderTranscriptHash = hash(Initiate)     — B signs over this
 *   - initiatorTranscriptHash = hash(Initiate, Accept) — A signs over this
 *
 * Verifies BOTH possession proofs (initiator + responder) against their
 * respective public keys and transcript hashes. If either fails, throws
 * — no artifact is produced, no WeakSet entry is created.
 *
 * This is the evidence that the 3-message handshake genuinely completed.
 */
export function createVerifiedTranscript(params: {
  initiateBytes: Uint8Array;
  acceptBytes: Uint8Array;
  linkIdBytes: Uint8Array;
  initiatorNodeId: string;
  responderNodeId: string;
  initiatorPublicKey: Uint8Array;
  responderPublicKey: Uint8Array;
  /** The challenge A generated for B (B signs this). */
  challengeForB: Uint8Array;
  /** The challenge B generated for A (A signs this). */
  challengeForA: Uint8Array;
  /** A's possession proof (signs challengeForA, role INITIATOR, over hash(Initiate, Accept)). */
  proofA: Uint8Array;
  /** B's possession proof (signs challengeForB, role RESPONDER, over hash(Initiate)). */
  proofB: Uint8Array;
  verifiedAt: number;
}): VerifiedTranscript {
  // Compute the two transcript hashes.
  // B signs over hash(Initiate) — B has only seen message_1 when it signs.
  const responderTranscriptHash = computeTranscriptHash([params.initiateBytes]);
  // A signs over hash(Initiate, Accept) — A has seen both messages.
  const initiatorTranscriptHash = computeTranscriptHash([params.initiateBytes, params.acceptBytes]);

  // 1. Verify the responder's (B's) possession proof over hash(Initiate).
  const proofBOk = verifyPossessionProof(
    params.responderPublicKey,
    params.proofB,
    POSSESSION_DOMAIN_RESPONDER,
    responderTranscriptHash,
    params.linkIdBytes,
    params.challengeForB,
    ROLE_RESPONDER,
  );
  if (!proofBOk) {
    throw new Error(
      "ARCHITECTURE VIOLATION: createVerifiedTranscript rejected — " +
        "responder's possession proof did not verify. The 3-message " +
        "handshake (per ADR-0016) requires B to sign the challenge " +
        "generated by A, bound to hash(Initiate) and the directional " +
        "LinkId, with role RESPONDER. An invalid or missing proof " +
        "means the handshake did not genuinely complete.",
    );
  }

  // 2. Verify the initiator's (A's) possession proof over hash(Initiate, Accept).
  const proofAOk = verifyPossessionProof(
    params.initiatorPublicKey,
    params.proofA,
    POSSESSION_DOMAIN_INITIATOR,
    initiatorTranscriptHash,
    params.linkIdBytes,
    params.challengeForA,
    ROLE_INITIATOR,
  );
  if (!proofAOk) {
    throw new Error(
      "ARCHITECTURE VIOLATION: createVerifiedTranscript rejected — " +
        "initiator's possession proof did not verify. The 3-message " +
        "handshake (per ADR-0016) requires A to sign the challenge " +
        "generated by B, bound to hash(Initiate, Accept) and the " +
        "directional LinkId, with role INITIATOR. An invalid or missing " +
        "proof means the handshake did not genuinely complete.",
    );
  }

  // Both proofs verified — register the genuine artifact.
  // The canonical transcript digest is the full hash(Initiate, Accept).
  const transcript: VerifiedTranscript = {
    transcriptDigestHex: toHex(initiatorTranscriptHash),
    linkIdHex: toHex(params.linkIdBytes),
    linkIdBytes: params.linkIdBytes,
    initiatorNodeId: params.initiatorNodeId,
    responderNodeId: params.responderNodeId,
    verifiedAt: params.verifiedAt,
  };
  verifiedTranscriptRegistry.add(transcript);
  return transcript;
}

/**
 * Runtime check: is this object a genuine VerifiedTranscript
 * produced by createVerifiedTranscript()?
 *
 * Uses WeakSet membership — genuinely unforgeable.
 */
export function isVerifiedTranscript(obj: unknown): obj is VerifiedTranscript {
  return typeof obj === "object" && obj !== null && verifiedTranscriptRegistry.has(obj);
}

// -----------------------------------------------------------------------
// AuthenticatedLink — binds a VerifiedTranscript to an AuthenticatedNodeRecord
// -----------------------------------------------------------------------

/**
 * An AuthenticatedLink is the proof that a directed link to a specific
 * authenticated node completed the 3-message handshake.
 *
 * It carries:
 *   - the genuine AuthenticatedNodeRecord of the REMOTE node
 *   - the local node's NodeId (directional: local → remote)
 *   - the directional LinkId (from the verified transcript)
 *   - the transcript digest (the cryptographic evidence binding)
 *   - establishment + expiry timestamps
 *
 * ValidatedHop now consumes an AuthenticatedLink (not a boolean) —
 * linkUp is no longer caller-supplied trust; it is implied by the
 * genuine link artifact.
 */
export interface AuthenticatedLink {
  readonly localNodeId: string;
  readonly remoteNodeId: string;
  readonly remoteNode: AuthenticatedNodeRecord;
  readonly linkIdHex: string;
  readonly linkIdBytes: Uint8Array;
  readonly transcriptDigestHex: string;
  readonly establishedAt: number;
  readonly expiresAt: number;
}

/**
 * The ONLY function that creates an AuthenticatedLink.
 *
 * Consumes:
 *   1. A genuine AuthenticatedNodeRecord (the remote node — WeakSet-verified)
 *   2. A genuine VerifiedTranscript (the handshake evidence — WeakSet-verified)
 *
 * Verifies that the transcript's remoteNodeId matches the authNode's nodeId.
 * Verifies that the transcript's linkId is bound to (localNodeId, remoteNodeId).
 *
 * If any check fails, throws — no artifact is produced.
 */
export function createAuthenticatedLink(params: {
  localNodeId: string;
  remoteNode: AuthenticatedNodeRecord;
  verifiedTranscript: VerifiedTranscript;
  establishedAt: number;
  expiresAt: number;
}): AuthenticatedLink {
  // 1. Verify the remoteNode is a genuine AuthenticatedNodeRecord.
  if (!isAuthenticatedNodeRecord(params.remoteNode)) {
    throw new Error(
      "ARCHITECTURE VIOLATION: createAuthenticatedLink rejected — " +
        "remoteNode is not a genuine AuthenticatedNodeRecord (WeakSet " +
        "membership check failed). Per R-002-P1, an AuthenticatedLink " +
        "requires a genuine authenticated node produced by " +
        "createAuthenticatedNodeRecord (which consumes a genuine " +
        "VerifiedNodeAdvertisement).",
    );
  }

  // 2. Verify the verifiedTranscript is genuine.
  if (!isVerifiedTranscript(params.verifiedTranscript)) {
    throw new Error(
      "ARCHITECTURE VIOLATION: createAuthenticatedLink rejected — " +
        "verifiedTranscript is not a genuine VerifiedTranscript (WeakSet " +
        "membership check failed). Per R-002-P1, an AuthenticatedLink " +
        "requires genuine handshake evidence produced by " +
        "createVerifiedTranscript (which verifies BOTH possession proofs).",
    );
  }

  // 3. The transcript's remote node must be the authenticated node.
  //    The transcript has initiatorNodeId + responderNodeId; the remote node
  //    is whichever of the two is NOT the local node.
  const { initiatorNodeId, responderNodeId } = params.verifiedTranscript;
  const remoteFromTranscript =
    initiatorNodeId === params.localNodeId
      ? responderNodeId
      : initiatorNodeId === params.localNodeId
        ? initiatorNodeId
        : null;

  if (remoteFromTranscript === null) {
    throw new Error(
      "ARCHITECTURE VIOLATION: createAuthenticatedLink rejected — " +
        `localNodeId (${params.localNodeId}) is neither the initiator ` +
        `(${initiatorNodeId}) nor the responder (${responderNodeId}) of ` +
        "the verified transcript. The local node must be a participant " +
        "in the handshake whose transcript is being bound.",
    );
  }

  if (remoteFromTranscript !== params.remoteNode.nodeId) {
    throw new Error(
      "ARCHITECTURE VIOLATION: createAuthenticatedLink rejected — " +
        `the transcript's remote node (${remoteFromTranscript}) does not ` +
        `match the AuthenticatedNodeRecord's nodeId (${params.remoteNode.nodeId}). ` +
        "The link must bind the transcript to the SAME node that was " +
        "authenticated — a transcript for a different node cannot " +
        "substitute.",
    );
  }

  const link: AuthenticatedLink = {
    localNodeId: params.localNodeId,
    remoteNodeId: params.remoteNode.nodeId,
    remoteNode: params.remoteNode,
    linkIdHex: params.verifiedTranscript.linkIdHex,
    linkIdBytes: params.verifiedTranscript.linkIdBytes,
    transcriptDigestHex: params.verifiedTranscript.transcriptDigestHex,
    establishedAt: params.establishedAt,
    expiresAt: params.expiresAt,
  };
  authenticatedLinkRegistry.add(link);
  return link;
}

/**
 * Runtime check: is this object a genuine AuthenticatedLink
 * produced by createAuthenticatedLink()?
 *
 * Uses WeakSet membership — genuinely unforgeable. There is no property
 * to copy, no value to forge.
 */
export function isAuthenticatedLink(obj: unknown): obj is AuthenticatedLink {
  return typeof obj === "object" && obj !== null && authenticatedLinkRegistry.has(obj);
}
