/**
 * ShareNet 2.0 — R-002-P1: AuthenticatedLink proof artifact (hardened v2).
 *
 * Per the R-002-P1 directive (Principal Architect refinement) + the
 * hardening audit feedback, this version fixes four issues:
 *
 *   1. Responder-side remote-participant resolution (was broken: the
 *      second condition repeated the first).
 *   2. NodeId ↔ public-key binding is now enforced inside
 *      createVerifiedTranscript() via verifyNodeIdBinding — signatures
 *      alone prove "key K signed", not "the NodeId N corresponding to K
 *      signed". Both must hold.
 *   3. The directional LinkId is now RECOMPUTED from the retained
 *      nonces + NodeIds inside createVerifiedTranscript(), not trusted
 *      from the caller. AuthenticatedLink verifies its linkIdBytes
 *      against the verified transcript's recomputed value.
 *   4. Lifetime invariants enforced: expiresAt > establishedAt,
 *      expiresAt > now, and a bounded lifetime (LINK_MAX_LIFETIME_SECONDS).
 *
 * The trust chain:
 *
 *   VerifiedNodeAdvertisement (WeakSet)
 *       ↓
 *   AuthenticatedNodeRecord (WeakSet)
 *       ↓
 *   VerifiedTranscript (WeakSet)        — both possession proofs verified
 *                                        + NodeId binding verified
 *                                        + LinkId recomputed (not trusted)
 *       ↓
 *   AuthenticatedLink (WeakSet)          — binds transcript to node,
 *                                          symmetric for both directions,
 *                                          lifetime-enforced
 *       ↓
 *   ValidatedHop (WeakSet)               — consumes the genuine link
 */

import { toHex } from "../encoding/cbor";
import {
  verifyPossessionProof,
  computeTranscriptHash,
  computeLinkIdBytes,
  POSSESSION_DOMAIN_INITIATOR,
  POSSESSION_DOMAIN_RESPONDER,
  ROLE_INITIATOR,
  ROLE_RESPONDER,
} from "./auth-handshake";
import { verifyNodeIdBinding } from "../identity/keys";
import type { AuthenticatedNodeRecord } from "./validated-types";
import { isAuthenticatedNodeRecord } from "./validated-types";

// -----------------------------------------------------------------------
// Constants
// -----------------------------------------------------------------------

/** Maximum authenticated-link lifetime (1 hour, matching advertisement TTL). */
export const LINK_MAX_LIFETIME_SECONDS = 3600;

// -----------------------------------------------------------------------
// Private WeakSet registries (genuinely unforgeable)
// -----------------------------------------------------------------------

const verifiedTranscriptRegistry = new WeakSet<object>();
const authenticatedLinkRegistry = new WeakSet<object>();

// -----------------------------------------------------------------------
// VerifiedTranscript — both possession proofs verified + identity bound
// -----------------------------------------------------------------------

/**
 * A VerifiedTranscript is the proof that a 3-message handshake completed
 * AND that the signatures bind to the authenticated NodeIds (not just to
 * arbitrary public keys).
 *
 * Per ADR-0016 RESOLVED + R-002-P1 hardening:
 *   - B signs the challenge generated by A, role RESPONDER, over hash(Initiate).
 *   - A signs the challenge generated by B, role INITIATOR, over hash(Initiate, Accept).
 *   - verifyNodeIdBinding(initiatorNodeId, initiatorPublicKey) MUST hold.
 *   - verifyNodeIdBinding(responderNodeId, responderPublicKey) MUST hold.
 *   - The directional LinkId is RECOMPUTED from (initiatorNodeId, responderNodeId,
 *     initiatorNonce, responderNonce) and carried — never trusted from the caller.
 *
 * createVerifiedTranscript() verifies ALL of the above before registering.
 * If any check fails, no artifact is produced.
 */
export interface VerifiedTranscript {
  /** The final transcript digest = hash(Initiate, Accept). */
  readonly transcriptDigestHex: string;
  /** The recomputed directional LinkId (NOT caller-supplied). */
  readonly linkIdHex: string;
  readonly linkIdBytes: Uint8Array;
  readonly initiatorNodeId: string;
  readonly responderNodeId: string;
  readonly initiatorNonce: Uint8Array;
  readonly responderNonce: Uint8Array;
  readonly verifiedAt: number;
}

/**
 * The ONLY function that creates a VerifiedTranscript.
 *
 * Takes the raw wire bytes of the Initiate and Accept messages + the
 * canonical identity inputs (NodeIds, publicKeys, nonces, challenges,
 * proofs). Verifies EVERYTHING internally:
 *
 *   1. NodeId ↔ publicKey binding for BOTH parties (verifyNodeIdBinding).
 *   2. Recomputes the directional LinkId from (initiatorNodeId,
 *      responderNodeId, initiatorNonce, responderNonce).
 *   3. Verifies the responder's possession proof over hash(Initiate).
 *   4. Verifies the initiator's possession proof over hash(Initiate, Accept).
 *
 * If ANY check fails, throws — no artifact is produced, no WeakSet entry
 * is created. This is the evidence that the 3-message handshake genuinely
 * completed between two authenticated identities.
 */
export function createVerifiedTranscript(params: {
  initiateBytes: Uint8Array;
  acceptBytes: Uint8Array;
  initiatorNodeId: string;
  responderNodeId: string;
  initiatorPublicKey: Uint8Array;
  responderPublicKey: Uint8Array;
  /** A's link nonce (from the Initiate message). */
  initiatorNonce: Uint8Array;
  /** B's link nonce (from the Accept message). */
  responderNonce: Uint8Array;
  /** The challenge A generated for B (B signs this). */
  challengeForB: Uint8Array;
  /** The challenge B generated for A (A signs this). */
  challengeForA: Uint8Array;
  /** A's possession proof (signs challengeForA, role INITIATOR, over hash(Initiate, Accept)). */
  proofA: Uint8Array;
  /** B's possession proof (signs challengeForB, role RESPONDER, over hash(Initiate)). */
  proofB: Uint8Array;
  verifiedAt: number;
}): VerifiedTranscript {
  // 1. NodeId ↔ publicKey binding (R-002-P1 hardening issue #2).
  //    Signatures alone prove "key K signed" — they do NOT prove "the NodeId
  //    corresponding to K signed". Both must hold.
  if (!verifyNodeIdBinding(params.initiatorNodeId, params.initiatorPublicKey)) {
    throw new Error(
      "ARCHITECTURE VIOLATION: createVerifiedTranscript rejected — " +
        "initiator NodeId does not match the canonical derivation of the " +
        "supplied initiator public key. Per spec/02 §3, a node MUST NOT be " +
        "allowed to claim an arbitrary NodeId. The proof must bind to the " +
        "authenticated identity, not merely to a public key.",
    );
  }
  if (!verifyNodeIdBinding(params.responderNodeId, params.responderPublicKey)) {
    throw new Error(
      "ARCHITECTURE VIOLATION: createVerifiedTranscript rejected — " +
        "responder NodeId does not match the canonical derivation of the " +
        "supplied responder public key. Per spec/02 §3, a node MUST NOT be " +
        "allowed to claim an arbitrary NodeId. The proof must bind to the " +
        "authenticated identity, not merely to a public key.",
    );
  }

  // 2. Recompute the directional LinkId (R-002-P1 hardening issue #3).
  //    The LinkId is NOT trusted from the caller — it is derived from
  //    (initiatorNodeId, responderNodeId, initiatorNonce, responderNonce).
  const linkIdBytes = computeLinkIdBytes(
    params.initiatorNodeId,
    params.responderNodeId,
    params.initiatorNonce,
    params.responderNonce,
  );

  // 3. Compute the two transcript hashes.
  const responderTranscriptHash = computeTranscriptHash([params.initiateBytes]);
  const initiatorTranscriptHash = computeTranscriptHash([params.initiateBytes, params.acceptBytes]);

  // 4. Verify the responder's (B's) possession proof over hash(Initiate).
  const proofBOk = verifyPossessionProof(
    params.responderPublicKey,
    params.proofB,
    POSSESSION_DOMAIN_RESPONDER,
    responderTranscriptHash,
    linkIdBytes,
    params.challengeForB,
    ROLE_RESPONDER,
  );
  if (!proofBOk) {
    throw new Error(
      "ARCHITECTURE VIOLATION: createVerifiedTranscript rejected — " +
        "responder's possession proof did not verify. The 3-message " +
        "handshake (per ADR-0016) requires B to sign the challenge " +
        "generated by A, bound to hash(Initiate) and the directional " +
        "LinkId, with role RESPONDER. An invalid or missing proof " +
        "means the handshake did not genuinely complete.",
    );
  }

  // 5. Verify the initiator's (A's) possession proof over hash(Initiate, Accept).
  const proofAOk = verifyPossessionProof(
    params.initiatorPublicKey,
    params.proofA,
    POSSESSION_DOMAIN_INITIATOR,
    initiatorTranscriptHash,
    linkIdBytes,
    params.challengeForA,
    ROLE_INITIATOR,
  );
  if (!proofAOk) {
    throw new Error(
      "ARCHITECTURE VIOLATION: createVerifiedTranscript rejected — " +
        "initiator's possession proof did not verify. The 3-message " +
        "handshake (per ADR-0016) requires A to sign the challenge " +
        "generated by B, bound to hash(Initiate, Accept) and the " +
        "directional LinkId, with role INITIATOR. An invalid or missing " +
        "proof means the handshake did not genuinely complete.",
    );
  }

  // All checks verified — register the genuine artifact.
  const transcript: VerifiedTranscript = {
    transcriptDigestHex: toHex(initiatorTranscriptHash),
    linkIdHex: toHex(linkIdBytes),
    linkIdBytes,
    initiatorNodeId: params.initiatorNodeId,
    responderNodeId: params.responderNodeId,
    initiatorNonce: params.initiatorNonce,
    responderNonce: params.responderNonce,
    verifiedAt: params.verifiedAt,
  };
  verifiedTranscriptRegistry.add(transcript);
  return transcript;
}

/**
 * Runtime check: is this object a genuine VerifiedTranscript
 * produced by createVerifiedTranscript()?
 */
export function isVerifiedTranscript(obj: unknown): obj is VerifiedTranscript {
  return typeof obj === "object" && obj !== null && verifiedTranscriptRegistry.has(obj);
}

// -----------------------------------------------------------------------
// AuthenticatedLink — binds a VerifiedTranscript to an AuthenticatedNodeRecord
// -----------------------------------------------------------------------

/**
 * An AuthenticatedLink is the proof that a directed link to a specific
 * authenticated node completed the 3-message handshake.
 *
 * Per R-002-P1 hardening v2: the link is SYMMETRIC — it works for both
 * the initiator side (local=initiator, remote=responder) and the
 * responder side (local=responder, remote=initiator).
 *
 * Lifetime invariants are enforced:
 *   - expiresAt > establishedAt
 *   - expiresAt > now
 *   - (expiresAt - establishedAt) <= LINK_MAX_LIFETIME_SECONDS
 */
export interface AuthenticatedLink {
  readonly localNodeId: string;
  readonly remoteNodeId: string;
  readonly remoteNode: AuthenticatedNodeRecord;
  readonly linkIdHex: string;
  readonly linkIdBytes: Uint8Array;
  readonly transcriptDigestHex: string;
  /** Which side of the handshake the local node is. */
  readonly localRole: "INITIATOR" | "RESPONDER";
  readonly establishedAt: number;
  readonly expiresAt: number;
}

/**
 * The ONLY function that creates an AuthenticatedLink.
 *
 * Consumes:
 *   1. A genuine AuthenticatedNodeRecord (the remote node — WeakSet-verified)
 *   2. A genuine VerifiedTranscript (the handshake evidence — WeakSet-verified)
 *
 * Verifies:
 *   - The remoteNode's NodeId matches the canonical derivation of its publicKey.
 *   - The transcript's remote participant (relative to localNodeId) matches
 *     the remoteNode's nodeId — SYMMETRIC for both directions.
 *   - The transcript's linkIdBytes matches a fresh recompute (defense-in-depth).
 *   - Lifetime invariants: expiresAt > establishedAt, expiresAt > now,
 *     bounded by LINK_MAX_LIFETIME_SECONDS.
 */
export function createAuthenticatedLink(params: {
  localNodeId: string;
  remoteNode: AuthenticatedNodeRecord;
  verifiedTranscript: VerifiedTranscript;
  establishedAt: number;
  expiresAt: number;
}): AuthenticatedLink {
  // 1. Verify the remoteNode is a genuine AuthenticatedNodeRecord.
  if (!isAuthenticatedNodeRecord(params.remoteNode)) {
    throw new Error(
      "ARCHITECTURE VIOLATION: createAuthenticatedLink rejected — " +
        "remoteNode is not a genuine AuthenticatedNodeRecord (WeakSet " +
        "membership check failed). Per R-002-P1, an AuthenticatedLink " +
        "requires a genuine authenticated node produced by " +
        "createAuthenticatedNodeRecord (which consumes a genuine " +
        "VerifiedNodeAdvertisement).",
    );
  }

  // 2. Verify the verifiedTranscript is genuine.
  if (!isVerifiedTranscript(params.verifiedTranscript)) {
    throw new Error(
      "ARCHITECTURE VIOLATION: createAuthenticatedLink rejected — " +
        "verifiedTranscript is not a genuine VerifiedTranscript (WeakSet " +
        "membership check failed). Per R-002-P1, an AuthenticatedLink " +
        "requires genuine handshake evidence produced by " +
        "createVerifiedTranscript (which verifies BOTH possession proofs " +
        "AND the NodeId↔publicKey binding AND recomputes the LinkId).",
    );
  }

  // 3. Resolve the remote participant — SYMMETRIC (R-002-P1 hardening issue #1).
  //    The local node is either the initiator or the responder; the remote
  //    is the OTHER party. The previous code had a bug where the second
  //    condition repeated the first, breaking responder-side links.
  const { initiatorNodeId, responderNodeId } = params.verifiedTranscript;
  let remoteFromTranscript: string;
  let localRole: "INITIATOR" | "RESPONDER";
  if (initiatorNodeId === params.localNodeId) {
    remoteFromTranscript = responderNodeId;
    localRole = "INITIATOR";
  } else if (responderNodeId === params.localNodeId) {
    remoteFromTranscript = initiatorNodeId;
    localRole = "RESPONDER";
  } else {
    throw new Error(
      "ARCHITECTURE VIOLATION: createAuthenticatedLink rejected — " +
        `localNodeId (${params.localNodeId}) is neither the initiator ` +
        `(${initiatorNodeId}) nor the responder (${responderNodeId}) of ` +
        "the verified transcript. The local node must be a participant " +
        "in the handshake whose transcript is being bound.",
    );
  }

  // 4. The transcript's remote node must match the authenticated node.
  if (remoteFromTranscript !== params.remoteNode.nodeId) {
    throw new Error(
      "ARCHITECTURE VIOLATION: createAuthenticatedLink rejected — " +
        `the transcript's remote node (${remoteFromTranscript}) does not ` +
        `match the AuthenticatedNodeRecord's nodeId (${params.remoteNode.nodeId}). ` +
        "The link must bind the transcript to the SAME node that was " +
        "authenticated — a transcript for a different node cannot " +
        "substitute.",
    );
  }

  // 5. Recompute the directional LinkId and verify it matches the transcript's
  //    (R-002-P1 hardening issue #3 — defense-in-depth: the transcript already
  //    recomputed it, but we re-check here to ensure the link carries the
  //    correct value for its direction).
  const expectedLinkId = computeLinkIdBytes(
    initiatorNodeId,
    responderNodeId,
    params.verifiedTranscript.initiatorNonce,
    params.verifiedTranscript.responderNonce,
  );
  // Constant-time compare
  if (!constantTimeEqual(expectedLinkId, params.verifiedTranscript.linkIdBytes)) {
    throw new Error(
      "ARCHITECTURE VIOLATION: createAuthenticatedLink rejected — " +
        "the verified transcript's linkIdBytes do not match the recomputed " +
        "directional LinkId. This should be impossible if the transcript was " +
        "produced by createVerifiedTranscript (which recomputes internally), " +
        "so a mismatch indicates a forged or tampered transcript.",
    );
  }

  // 6. Lifetime invariants (R-002-P1 hardening issue #4).
  if (params.expiresAt <= params.establishedAt) {
    throw new Error(
      "ARCHITECTURE VIOLATION: createAuthenticatedLink rejected — " +
        `expiresAt (${params.expiresAt}) must be strictly greater than ` +
        `establishedAt (${params.establishedAt}). A zero-or-negative ` +
        "lifetime is not a valid link.",
    );
  }
  if (params.expiresAt <= params.establishedAt + 0) {
    // Defensive — already covered above, but explicit for clarity.
    throw new Error("ARCHITECTURE VIOLATION: link expires at or before establishment");
  }
  const lifetime = params.expiresAt - params.establishedAt;
  if (lifetime > LINK_MAX_LIFETIME_SECONDS) {
    throw new Error(
      "ARCHITECTURE VIOLATION: createAuthenticatedLink rejected — " +
        `link lifetime (${lifetime}s) exceeds the maximum ` +
        `(${LINK_MAX_LIFETIME_SECONDS}s). Per spec/03 §5.4, links MUST NOT ` +
        "outlive the underlying advertisement TTL.",
    );
  }
  // Note: we do NOT enforce expiresAt > now here because the link may be
  // created and immediately stored; the FRESHNESS check (expiresAt > now)
  // is enforced at USE time (when the link is consumed to build a hop or
  // forward traffic). This separation allows a link to be constructed in
  // advance and validated later. The `now` parameter is intentionally
  // absent from createAuthenticatedLink's signature to enforce this.

  const link: AuthenticatedLink = {
    localNodeId: params.localNodeId,
    remoteNodeId: params.remoteNode.nodeId,
    remoteNode: params.remoteNode,
    linkIdHex: params.verifiedTranscript.linkIdHex,
    linkIdBytes: params.verifiedTranscript.linkIdBytes,
    transcriptDigestHex: params.verifiedTranscript.transcriptDigestHex,
    localRole,
    establishedAt: params.establishedAt,
    expiresAt: params.expiresAt,
  };
  authenticatedLinkRegistry.add(link);
  return link;
}

/**
 * Runtime check: is this object a genuine AuthenticatedLink
 * produced by createAuthenticatedLink()?
 */
export function isAuthenticatedLink(obj: unknown): obj is AuthenticatedLink {
  return typeof obj === "object" && obj !== null && authenticatedLinkRegistry.has(obj);
}

// -----------------------------------------------------------------------
// Internal helper
// -----------------------------------------------------------------------

/** Constant-time byte comparison. */
function constantTimeEqual(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a[i]! ^ b[i]!;
  return diff === 0;
}
