/**
 * ShareNet 2.0 — Authenticated Link Handshake (3-message, transcript-bound).
 *
 * Per ADR-0016 (RESOLVED — Principal Architect approved via roadmap §B):
 *
 *   The current two-message exchange is only ADV_VERIFIED, never LINK_UP.
 *   Implement authenticated links only using this three-message design:
 *
 *   1. Initiator → Responder, Initiate
 *      - canonical advertisement bytes for A
 *      - link_nonce_A: 16 random bytes
 *      - challenge_for_B: 32 random bytes
 *
 *   2. Responder → Initiator, Accept
 *      - canonical advertisement bytes for B
 *      - link_nonce_B: 16 random bytes
 *      - challenge_for_A: 32 random bytes
 *      - proof_B: Ed25519 signature by B over B's possession payload
 *
 *   3. Initiator → Responder, Confirm
 *      - proof_A: Ed25519 signature by A over A's possession payload
 *
 * Transcript framing:
 *   transcript_hash = BLAKE3-256(
 *     utf8("SHARENET/LINK/TRANSCRIPT/1")
 *     || u32be(length(message_1)) || message_1
 *     || u32be(length(message_2)) || message_2
 *     || ...
 *   )
 *
 * Possession payload (what each party signs):
 *   utf8(role-specific domain tag)
 *   || transcript_hash           (32 bytes)
 *   || directional_link_id_bytes (32 bytes)
 *   || peer_generated_challenge  (32 bytes)
 *   || role_byte                 (1 byte: 0x01 = INITIATOR, 0x02 = RESPONDER)
 *
 * Domain tags:
 *   SHARENET/LINK/POSSESSION/INITIATOR/1
 *   SHARENET/LINK/POSSESSION/RESPONDER/1
 *
 * Rules:
 *   - Each party signs the challenge generated by the peer, never its own.
 *   - A LINK_UP record exists only after both proofs verify.
 *   - ADV_VERIFIED is not routable.
 */

import { blake3 } from "@noble/hashes/blake3.js";
import { ed25519 } from "@noble/curves/ed25519.js";
import { randomBytes } from "@noble/hashes/utils.js";
import { canonicalEncode, canonicalDecode, toHex, fromHex } from "../encoding/cbor";
import { verifyAdvertisement, advertisementFromHex, advertisementToHex, type NodeAdvertisement } from "../advertisement/advertisement";
import { deriveNodeId, verifySignature, signMessage, type NodeKeypair } from "../identity/keys";

// -----------------------------------------------------------------------
// Constants (FROZEN per ADR-0016 RESOLVED)
// -----------------------------------------------------------------------

/** Domain tag for transcript hashing. */
export const TRANSCRIPT_DOMAIN = "SHARENET/LINK/TRANSCRIPT/1";

/** Domain tag for the initiator's possession proof. */
export const POSSESSION_DOMAIN_INITIATOR = "SHARENET/LINK/POSSESSION/INITIATOR/1";

/** Domain tag for the responder's possession proof. */
export const POSSESSION_DOMAIN_RESPONDER = "SHARENET/LINK/POSSESSION/RESPONDER/1";

/** Role byte for the initiator. */
export const ROLE_INITIATOR = 0x01;

/** Role byte for the responder. */
export const ROLE_RESPONDER = 0x02;

/** Size of a link nonce (16 bytes). */
export const LINK_NONCE_BYTES = 16;

/** Size of a challenge (32 bytes). */
export const CHALLENGE_BYTES = 32;

/** Size of an Ed25519 signature (64 bytes). */
export const SIGNATURE_BYTES = 64;

/** Challenge expiration in milliseconds (5 minutes). */
export const CHALLENGE_EXPIRY_MS = 5 * 60 * 1000;

// -----------------------------------------------------------------------
// CBOR message types (integer-keyed maps per ADR-0004)
// -----------------------------------------------------------------------

export const MSG_KIND = {
  INITIATE: 1,
  ACCEPT: 2,
  CONFIRM: 3,
} as const;

/**
 * Message 1: Initiate (Initiator → Responder).
 * Contains A's advertisement + A's link nonce + A's challenge for B.
 */
export interface InitiateMessage {
  kind: typeof MSG_KIND.INITIATE;
  advertisementHex: string;       // canonical CBOR hex of A's signed advertisement
  linkNonceA: Uint8Array;        // 16 bytes — A's link nonce for LinkId derivation
  challengeForB: Uint8Array;      // 32 bytes — A generates this; B will sign it
}

/**
 * Message 2: Accept (Responder → Initiator).
 * Contains B's advertisement + B's link nonce + B's challenge for A + B's possession proof.
 */
export interface AcceptMessage {
  kind: typeof MSG_KIND.ACCEPT;
  advertisementHex: string;       // canonical CBOR hex of B's signed advertisement
  linkNonceB: Uint8Array;         // 16 bytes — B's link nonce for LinkId derivation
  challengeForA: Uint8Array;       // 32 bytes — B generates this; A will sign it
  proofB: Uint8Array;              // 64 bytes — Ed25519 signature by B
}

/**
 * Message 3: Confirm (Initiator → Responder).
 * Contains A's possession proof.
 */
export interface ConfirmMessage {
  kind: typeof MSG_KIND.CONFIRM;
  proofA: Uint8Array;              // 64 bytes — Ed25519 signature by A
}

// -----------------------------------------------------------------------
// Wire encoding/decoding (canonical CBOR, integer-keyed maps)
// -----------------------------------------------------------------------

export function encodeInitiate(msg: InitiateMessage): Uint8Array {
  const m = new Map<number, unknown>([
    [1, msg.kind],
    [2, msg.advertisementHex],
    [3, msg.linkNonceA],
    [4, msg.challengeForB],
  ]);
  return canonicalEncode(m);
}

export function encodeAccept(msg: AcceptMessage): Uint8Array {
  const m = new Map<number, unknown>([
    [1, msg.kind],
    [2, msg.advertisementHex],
    [3, msg.linkNonceB],
    [4, msg.challengeForA],
    [5, msg.proofB],
  ]);
  return canonicalEncode(m);
}

export function encodeConfirm(msg: ConfirmMessage): Uint8Array {
  const m = new Map<number, unknown>([
    [1, msg.kind],
    [2, msg.proofA],
  ]);
  return canonicalEncode(m);
}

export function decodeMessage(bytes: Uint8Array): InitiateMessage | AcceptMessage | ConfirmMessage {
  const m = canonicalDecode<Map<number, unknown>>(bytes);
  if (!(m instanceof Map)) throw new Error("message is not a CBOR map");
  const kind = m.get(1) as number;
  if (kind === MSG_KIND.INITIATE) {
    return {
      kind,
      advertisementHex: m.get(2) as string,
      linkNonceA: new Uint8Array(m.get(3) as number[]),
      challengeForB: new Uint8Array(m.get(4) as number[]),
    };
  }
  if (kind === MSG_KIND.ACCEPT) {
    return {
      kind,
      advertisementHex: m.get(2) as string,
      linkNonceB: new Uint8Array(m.get(3) as number[]),
      challengeForA: new Uint8Array(m.get(4) as number[]),
      proofB: new Uint8Array(m.get(5) as number[]),
    };
  }
  if (kind === MSG_KIND.CONFIRM) {
    return {
      kind,
      proofA: new Uint8Array(m.get(2) as number[]),
    };
  }
  throw new Error(`unknown message kind: ${kind}`);
}

// -----------------------------------------------------------------------
// Transcript hash
// -----------------------------------------------------------------------

/**
 * Compute the transcript hash over a sequence of wire-encoded messages.
 *
 * transcript_hash = BLAKE3-256(
 *   utf8("SHARENET/LINK/TRANSCRIPT/1")
 *   || u32be(length(message_1)) || message_1
 *   || u32be(length(message_2)) || message_2
 *   || ...
 * )
 */
export function computeTranscriptHash(messages: Uint8Array[]): Uint8Array {
  const h = blake3.create({ dkLen: 32 });
  const domain = new TextEncoder().encode(TRANSCRIPT_DOMAIN);
  h.update(domain);
  for (const msg of messages) {
    // u32be length prefix
    const lenBuf = new Uint8Array(4);
    new DataView(lenBuf.buffer).setUint32(0, msg.length, false); // big-endian
    h.update(lenBuf);
    h.update(msg);
  }
  return h.digest();
}

// -----------------------------------------------------------------------
// Possession payload construction + verification
// -----------------------------------------------------------------------

/**
 * Build the possession payload that a party signs.
 *
 * payload = utf8(domain_tag)
 *   || transcript_hash           (32 bytes)
 *   || directional_link_id_bytes (32 bytes)
 *   || peer_generated_challenge  (32 bytes)
 *   || role_byte                 (1 byte)
 */
export function buildPossessionPayload(
  domainTag: string,
  transcriptHash: Uint8Array,
  linkIdBytes: Uint8Array,
  peerChallenge: Uint8Array,
  roleByte: number,
): Uint8Array {
  const tag = new TextEncoder().encode(domainTag);
  const out = new Uint8Array(tag.length + 32 + 32 + 32 + 1);
  let off = 0;
  out.set(tag, off); off += tag.length;
  out.set(transcriptHash, off); off += 32;
  out.set(linkIdBytes, off); off += 32;
  out.set(peerChallenge, off); off += 32;
  out[off] = roleByte;
  return out;
}

/**
 * Compute the directional LinkId bytes (BLAKE3-256 of local/remote NodeId + nonces).
 * This is the RAW bytes (not the text form) used in the possession payload.
 */
export function computeLinkIdBytes(
  localNodeId: string,
  remoteNodeId: string,
  localNonce: Uint8Array,
  remoteNonce: Uint8Array,
): Uint8Array {
  const h = blake3.create({ dkLen: 32 });
  h.update(new TextEncoder().encode("SHARENET/LINK/ID/1"));
  h.update(new TextEncoder().encode(localNodeId));
  h.update(new TextEncoder().encode(remoteNodeId));
  h.update(localNonce);
  h.update(remoteNonce);
  return h.digest();
}

/**
 * Sign a possession proof.
 * The signer signs the peer-generated challenge (never its own).
 */
export function signPossessionProof(
  secretKey: Uint8Array,
  domainTag: string,
  transcriptHash: Uint8Array,
  linkIdBytes: Uint8Array,
  peerChallenge: Uint8Array,
  roleByte: number,
): Uint8Array {
  const payload = buildPossessionPayload(domainTag, transcriptHash, linkIdBytes, peerChallenge, roleByte);
  return ed25519.sign(payload, secretKey);
}

/**
 * Verify a possession proof.
 * Returns true if the signature is valid under the given public key.
 */
export function verifyPossessionProof(
  publicKey: Uint8Array,
  signature: Uint8Array,
  domainTag: string,
  transcriptHash: Uint8Array,
  linkIdBytes: Uint8Array,
  peerChallenge: Uint8Array,
  roleByte: number,
): boolean {
  if (signature.length !== SIGNATURE_BYTES) return false;
  if (publicKey.length !== 32) return false;
  const payload = buildPossessionPayload(domainTag, transcriptHash, linkIdBytes, peerChallenge, roleByte);
  try {
    return ed25519.verify(signature, payload, publicKey);
  } catch {
    return false;
  }
}

// -----------------------------------------------------------------------
// Challenge cache (replay protection)
// -----------------------------------------------------------------------

interface ChallengeEntry {
  challenge: Uint8Array;
  createdAt: number;
  used: boolean;
}

/**
 * In-memory challenge cache for replay protection.
 *
 * Per ADR-0016:
 *   - Challenges expire after 5 minutes (CHALLENGE_EXPIRY_MS).
 *   - Each challenge is single-use. Once a proof is received, it's marked used.
 *   - A replayed challenge (same bytes seen twice) is rejected.
 */
export class ChallengeCache {
  private entries = new Map<string, ChallengeEntry>();
  private peerDenylist = new Map<string, number>(); // nodeId -> denylistUntil

  /**
   * Generate and store a fresh challenge for the peer to sign.
   * Returns the challenge bytes (32 random bytes).
   */
  generateChallenge(): Uint8Array {
    return randomBytes(CHALLENGE_BYTES);
  }

  /**
   * Verify that a challenge is valid (exists, not expired, not used).
   * If valid, mark it as used.
   */
  consumeChallenge(challenge: Uint8Array): { ok: true } | { ok: false; reason: string } {
    const key = toHex(challenge);
    const entry = this.entries.get(key);
    if (!entry) {
      return { ok: false, reason: "challenge_not_found" };
    }
    const now = Date.now();
    if (now - entry.createdAt > CHALLENGE_EXPIRY_MS) {
      this.entries.delete(key);
      return { ok: false, reason: "challenge_expired" };
    }
    if (entry.used) {
      return { ok: false, reason: "challenge_replayed" };
    }
    entry.used = true;
    return { ok: true };
  }

  /**
   * Register a challenge that we generated and sent to the peer.
   * We expect to receive a proof over this challenge back.
   */
  registerChallenge(challenge: Uint8Array): void {
    const key = toHex(challenge);
    this.entries.set(key, {
      challenge,
      createdAt: Date.now(),
      used: false,
    });
  }

  /**
   * Check if a peer is denylisted.
   */
  isDenylisted(nodeId: string): boolean {
    const until = this.peerDenylist.get(nodeId);
    if (!until) return false;
    if (Date.now() > until) {
      this.peerDenylist.delete(nodeId);
      return false;
    }
    return true;
  }

  /**
   * Add a peer to the denylist for a duration.
   */
  denylist(nodeId: string, durationMs: number = 5 * 60 * 1000): void {
    this.peerDenylist.set(nodeId, Date.now() + durationMs);
  }

  /**
   * Purge expired challenges (call periodically).
   */
  purgeExpired(): void {
    const now = Date.now();
    for (const [key, entry] of this.entries) {
      if (now - entry.createdAt > CHALLENGE_EXPIRY_MS) {
        this.entries.delete(key);
      }
    }
  }
}

// -----------------------------------------------------------------------
// High-level handshake state machine
// -----------------------------------------------------------------------

export type HandshakeError =
  | "ADV_VERIFICATION_FAILED"
  | "PROOF_INVALID"
  | "WRONG_ROLE"
  | "WRONG_LINK_ID"
  | "CHALLENGE_EXPIRED"
  | "CHALLENGE_REPLAYED"
  | "CHALLENGE_NOT_FOUND"
  | "PEER_DENYLISTED"
  | "MALFORMED_MESSAGE";

export interface LinkUpRecord {
  linkIdBytes: Uint8Array;
  linkIdHex: string;
  localNodeId: string;
  remoteNodeId: string;
  remotePublicKey: Uint8Array;
  remoteCapabilities: readonly string[];
  establishedAt: number;
}

/**
 * Build the Initiate message (step 1).
 * Called by the initiator.
 */
export function buildInitiate(
  localAdvertisement: NodeAdvertisement,
  linkNonceA: Uint8Array,
  challengeForB: Uint8Array,
): InitiateMessage {
  if (linkNonceA.length !== LINK_NONCE_BYTES) throw new Error("linkNonceA must be 16 bytes");
  if (challengeForB.length !== CHALLENGE_BYTES) throw new Error("challengeForB must be 32 bytes");
  return {
    kind: MSG_KIND.INITIATE,
    advertisementHex: toHex(canonicalEncode(advertisementToCborHex(localAdvertisement))),
    linkNonceA,
    challengeForB,
  };
}

/** Helper: convert a NodeAdvertisement to its canonical CBOR hex. */
function advertisementToCborHex(adv: NodeAdvertisement): Map<number, unknown> {
  // This is a placeholder — the actual encoding is in advertisement.ts
  // For the handshake, we pass the hex string directly.
  return new Map();
}

/**
 * Process an Initiate message and build the Accept message (step 2).
 * Called by the responder.
 *
 * Verifies A's advertisement, generates B's nonce + challenge, computes the
 * transcript hash, signs B's possession proof, and returns the Accept message.
 */
export function processInitiateAndBuildAccept(
  initiateBytes: Uint8Array,
  localAdvertisement: NodeAdvertisement,
  localKeypair: NodeKeypair,
  linkNonceB: Uint8Array,
  challengeForA: Uint8Array,
  referenceNow: number,
): { ok: true; accept: Uint8Array; remoteAdv: NodeAdvertisement; linkIdBytes: Uint8Array } | { ok: false; error: HandshakeError; detail: string } {
  // Decode the Initiate message
  let initiate: InitiateMessage;
  try {
    initiate = decodeMessage(initiateBytes) as InitiateMessage;
    if (initiate.kind !== MSG_KIND.INITIATE) {
      return { ok: false, error: "MALFORMED_MESSAGE", detail: "expected INITIATE" };
    }
  } catch (e) {
    return { ok: false, error: "MALFORMED_MESSAGE", detail: (e as Error).message };
  }

  // Verify A's advertisement
  // We need to parse the advertisement from hex. Import lazily to avoid circular deps.
  let remoteAdv: NodeAdvertisement;
  try {
    remoteAdv = advertisementFromHex(initiate.advertisementHex);
  } catch (e) {
    return { ok: false, error: "ADV_VERIFICATION_FAILED", detail: `decode: ${(e as Error).message}` };
  }

  const v = verifyAdvertisement(remoteAdv, referenceNow);
  if (!v.ok) {
    return { ok: false, error: "ADV_VERIFICATION_FAILED", detail: v.detail };
  }

  // Compute LinkId bytes (directional: local=B, remote=A)
  const linkIdBytes = computeLinkIdBytes(
    localKeypair.nodeId,
    remoteAdv.nodeId,
    linkNonceB,
    initiate.linkNonceA,
  );

  // Compute transcript hash (just the Initiate message so far)
  const transcriptHash = computeTranscriptHash([initiateBytes]);

  // B signs the challenge generated by A (initiate.challengeForB)
  const proofB = signPossessionProof(
    localKeypair.secretKey,
    POSSESSION_DOMAIN_RESPONDER,
    transcriptHash,
    linkIdBytes,
    initiate.challengeForB,
    ROLE_RESPONDER,
  );

  // Build the Accept message
  const accept: AcceptMessage = {
    kind: MSG_KIND.ACCEPT,
    advertisementHex: toHex(fromHex(localAdvertisementHex(localAdvertisement))),
    linkNonceB,
    challengeForA,
    proofB,
  };

  const acceptBytes = encodeAccept(accept);
  return { ok: true, accept: acceptBytes, remoteAdv, linkIdBytes };
}

/** Helper: get the canonical CBOR hex of a local advertisement. */
function localAdvertisementHex(adv: NodeAdvertisement): string {
  // Re-export from advertisement module
  return advertisementToHex(adv);
}

/**
 * Process an Accept message and build the Confirm message (step 3).
 * Called by the initiator.
 *
 * Verifies B's advertisement + B's possession proof, then signs A's possession proof.
 */
export function processAcceptAndBuildConfirm(
  initiateBytes: Uint8Array,
  acceptBytes: Uint8Array,
  localKeypair: NodeKeypair,
  localAdvertisement: NodeAdvertisement,
  initiateLinkNonceA: Uint8Array,
  initiateChallengeForB: Uint8Array,
  referenceNow: number,
): { ok: true; confirm: Uint8Array; remoteAdv: NodeAdvertisement; linkIdBytes: Uint8Array } | { ok: false; error: HandshakeError; detail: string } {
  // Decode the Accept message
  let accept: AcceptMessage;
  try {
    accept = decodeMessage(acceptBytes) as AcceptMessage;
    if (accept.kind !== MSG_KIND.ACCEPT) {
      return { ok: false, error: "MALFORMED_MESSAGE", detail: "expected ACCEPT" };
    }
  } catch (e) {
    return { ok: false, error: "MALFORMED_MESSAGE", detail: (e as Error).message };
  }

  // Verify B's advertisement
  let remoteAdv: NodeAdvertisement;
  try {
    remoteAdv = advertisementFromHex(accept.advertisementHex);
  } catch (e) {
    return { ok: false, error: "ADV_VERIFICATION_FAILED", detail: `decode: ${(e as Error).message}` };
  }

  const v = verifyAdvertisement(remoteAdv, referenceNow);
  if (!v.ok) {
    return { ok: false, error: "ADV_VERIFICATION_FAILED", detail: v.detail };
  }

  // Compute LinkId bytes (directional: local=A, remote=B)
  const linkIdBytes = computeLinkIdBytes(
    localKeypair.nodeId,
    remoteAdv.nodeId,
    initiateLinkNonceA,
    accept.linkNonceB,
  );

  // Compute transcript hash (Initiate + Accept)
  const transcriptHash = computeTranscriptHash([initiateBytes, acceptBytes]);

  // Verify B's possession proof
  // B signed: challenge_for_B (generated by A), with role RESPONDER
  const proofOk = verifyPossessionProof(
    remoteAdv.signingPublicKey,
    accept.proofB,
    POSSESSION_DOMAIN_RESPONDER,
    transcriptHash,
    linkIdBytes,
    initiateChallengeForB,
    ROLE_RESPONDER,
  );
  if (!proofOk) {
    return { ok: false, error: "PROOF_INVALID", detail: "B's possession proof did not verify" };
  }

  // A signs the challenge generated by B (accept.challengeForA)
  const proofA = signPossessionProof(
    localKeypair.secretKey,
    POSSESSION_DOMAIN_INITIATOR,
    transcriptHash,
    linkIdBytes,
    accept.challengeForA,
    ROLE_INITIATOR,
  );

  const confirm: ConfirmMessage = { kind: MSG_KIND.CONFIRM, proofA };
  const confirmBytes = encodeConfirm(confirm);
  return { ok: true, confirm: confirmBytes, remoteAdv, linkIdBytes };
}

/**
 * Process a Confirm message (step 3, responder side).
 * Verifies A's possession proof. If valid, LINK_UP is established.
 */
export function processConfirm(
  initiateBytes: Uint8Array,
  acceptBytes: Uint8Array,
  confirmBytes: Uint8Array,
  responderKeypair: NodeKeypair,
  initiatorAdv: NodeAdvertisement,
  linkNonceB: Uint8Array,
  linkNonceA: Uint8Array,
  challengeForA: Uint8Array,
  referenceNow: number,
): { ok: true; linkUp: LinkUpRecord } | { ok: false; error: HandshakeError; detail: string } {
  // Decode the Confirm message
  let confirm: ConfirmMessage;
  try {
    confirm = decodeMessage(confirmBytes) as ConfirmMessage;
    if (confirm.kind !== MSG_KIND.CONFIRM) {
      return { ok: false, error: "MALFORMED_MESSAGE", detail: "expected CONFIRM" };
    }
  } catch (e) {
    return { ok: false, error: "MALFORMED_MESSAGE", detail: (e as Error).message };
  }

  // Compute LinkId bytes (directional: local=B, remote=A)
  const linkIdBytes = computeLinkIdBytes(
    responderKeypair.nodeId,
    initiatorAdv.nodeId,
    linkNonceB,
    linkNonceA,
  );

  // Compute transcript hash (Initiate + Accept)
  const transcriptHash = computeTranscriptHash([initiateBytes, acceptBytes]);

  // Verify A's possession proof
  // A signed: challenge_for_A (generated by B), with role INITIATOR
  const proofOk = verifyPossessionProof(
    initiatorAdv.signingPublicKey,
    confirm.proofA,
    POSSESSION_DOMAIN_INITIATOR,
    transcriptHash,
    linkIdBytes,
    challengeForA,
    ROLE_INITIATOR,
  );
  if (!proofOk) {
    return { ok: false, error: "PROOF_INVALID", detail: "A's possession proof did not verify" };
  }

  // Both proofs verified — LINK_UP established
  return {
    ok: true,
    linkUp: {
      linkIdBytes,
      linkIdHex: toHex(linkIdBytes),
      localNodeId: responderKeypair.nodeId,
      remoteNodeId: initiatorAdv.nodeId,
      remotePublicKey: initiatorAdv.signingPublicKey,
      remoteCapabilities: initiatorAdv.capabilities,
      establishedAt: Date.now(),
    },
  };
}

// Re-export helpers used by the mini-service
export { randomBytes, toHex, fromHex, canonicalEncode, canonicalDecode };
