/**
 * ShareNet 2.0 — Shared test helper: genuine BrandedCommittedRoute pipeline.
 *
 * Per R-002-P1 + R-006 construction-boundary fix: the full proof-carrying
 * pipeline now runs a genuine 3-message handshake per hop, producing a
 * VerifiedTranscript + AuthenticatedLink before each ValidatedHop:
 *
 *   generateNodeKeypair (per hop + initiator)
 *       ↓
 *   signAdvertisement → verifyAdvertisement → VerifiedNodeAdvertisement (WeakSet)
 *       ↓
 *   createAuthenticatedNodeRecord → AuthenticatedNodeRecord (WeakSet)
 *       ↓
 *   3-message handshake (Initiate → Accept → Confirm)
 *       ↓
 *   createVerifiedTranscript (verifies BOTH possession proofs) → VerifiedTranscript (WeakSet)
 *       ↓
 *   createAuthenticatedLink → AuthenticatedLink (WeakSet)
 *       ↓
 *   createValidatedHop(link, ...) → ValidatedHop (WeakSet)
 *       ↓
 *   RouteProposal (RouteHop[] derived from the same fields)
 *       ↓
 *   signRouteAcceptance × N
 *       ↓
 *   createRouteCommitment → RouteCommitment (WeakSet)
 *       ↓
 *   createBrandedCommittedRoute(commitment, validatedHops) → BrandedCommittedRoute (WeakSet)
 */

import {
  generateNodeKeypair,
  randomBytes,
  bytesToHex,
  type NodeKeypair,
} from "@reference/identity/keys";
import {
  signAdvertisement,
  verifyAdvertisement,
  advertisementToHex,
} from "@reference/advertisement/advertisement";
import {
  type RouteHop,
  type RouteProposal,
  type RouteCommitment,
  signRouteAcceptance,
  createRouteCommitment,
} from "@reference/routing/route";
import type { ServiceAgreement } from "@reference/routing/service-negotiation";
import type { NodeCapability } from "@reference/identity/keys";
import { serviceDigest } from "@reference/routing/digests";
import { toHex } from "@reference/encoding/cbor";
import {
  createAuthenticatedNodeRecord,
  createValidatedHop,
  createBrandedCommittedRoute,
  type AuthenticatedNodeRecord,
  type ValidatedHop,
  type BrandedCommittedRoute,
} from "@reference/transport/validated-types";
import {
  computeTranscriptHash,
  computeLinkIdBytes,
  signPossessionProof,
  encodeInitiate,
  encodeAccept,
  ChallengeCache,
  POSSESSION_DOMAIN_INITIATOR,
  POSSESSION_DOMAIN_RESPONDER,
  ROLE_INITIATOR,
  ROLE_RESPONDER,
  type InitiateMessage,
  type AcceptMessage,
} from "@reference/transport/auth-handshake";
import {
  createVerifiedTranscript,
  createAuthenticatedLink,
  consumeChallengeForTranscript,
  type AuthenticatedLink,
  type VerifiedTranscript,
  type ConsumedChallenge,
} from "@reference/transport/authenticated-link";

export const BRANDED_ROUTE_HELPER_NOW = 1786876545;

export interface BrandedRouteContext {
  branded: BrandedCommittedRoute;
  commitment: RouteCommitment;
  proposal: RouteProposal;
  hops: RouteHop[];
  validatedHops: ValidatedHop[];
  authenticatedLinks: AuthenticatedLink[];
  verifiedTranscripts: VerifiedTranscript[];
  authNodes: AuthenticatedNodeRecord[];
  kps: NodeKeypair[];
  initiator: NodeKeypair;
  hopPublicKeys: Map<string, Uint8Array>;
  serviceAgreements: Map<number, ServiceAgreement>;
  capabilities: NodeCapability[];
  now: number;
}

/**
 * Run a full 3-message authenticated handshake between the initiator
 * (local) and a remote hop node, producing a genuine VerifiedTranscript.
 *
 * Per ADR-0016 RESOLVED:
 *   1. Initiate (initiator → responder): advA + nonceA + challengeForB
 *   2. Accept  (responder → initiator): advB + nonceB + challengeForA + proofB
 *   3. Confirm (initiator → responder): proofA
 *
 * The transcript hash covers Initiate + Accept. Each party signs the
 * PEER-generated challenge, bound to (transcriptHash, linkIdBytes, role).
 */
function runHandshake(
  initiatorKp: NodeKeypair,
  responderKp: NodeKeypair,
  initiatorAdvHex: string,
  responderAdvHex: string,
  now: number,
): VerifiedTranscript {
  const linkNonceA = randomBytes(16);
  const linkNonceB = randomBytes(16);
  const challengeForB = randomBytes(32); // A generates; B signs
  const challengeForA = randomBytes(32); // B generates; A signs

  // Step 1: Initiate (A → B)
  const initiateMsg: InitiateMessage = {
    kind: 1, // MSG_KIND.INITIATE
    advertisementHex: initiatorAdvHex,
    linkNonceA,
    challengeForB,
  };
  const initiateBytes = encodeInitiate(initiateMsg);

  // Directional LinkId (local=A=initiator, remote=B=responder)
  const linkIdBytes = computeLinkIdBytes(
    initiatorKp.nodeId, responderKp.nodeId, linkNonceA, linkNonceB,
  );

  // Transcript hash after Initiate
  const transcriptAfterInitiate = computeTranscriptHash([initiateBytes]);

  // Step 2: B signs challengeForB (generated by A), role RESPONDER
  const proofB = signPossessionProof(
    responderKp.secretKey, POSSESSION_DOMAIN_RESPONDER,
    transcriptAfterInitiate, linkIdBytes, challengeForB, ROLE_RESPONDER,
  );

  const acceptMsg: AcceptMessage = {
    kind: 2, // MSG_KIND.ACCEPT
    advertisementHex: responderAdvHex,
    linkNonceB, challengeForA, proofB,
  };
  const acceptBytes = encodeAccept(acceptMsg);

  // Transcript hash after Initiate + Accept (A signs over this)
  const transcriptAfterAccept = computeTranscriptHash([initiateBytes, acceptBytes]);

  // Step 3: A signs challengeForA (generated by B), role INITIATOR,
  // over hash(Initiate, Accept)
  const proofA = signPossessionProof(
    initiatorKp.secretKey, POSSESSION_DOMAIN_INITIATOR,
    transcriptAfterAccept, linkIdBytes, challengeForA, ROLE_INITIATOR,
  );

  // R-002-P1 hardening v4: consume the challenge from a ChallengeCache to
  // produce a ConsumedChallenge proof artifact (intrinsic freshness/replay proof).
  // The initiator (A) generated challengeForB, so A consumes it from A's cache
  // (signerRole=RESPONDER because B signed it).
  // R-002-P1 hardening v7: verifierNodeId is carried inside the ConsumedChallenge
  // — the initiator (A) is the freshness verifier.
  const cache = new ChallengeCache();
  cache.registerChallenge(challengeForB, now * 1000); // ChallengeCache uses ms
  const consumedChallenge = consumeChallengeForTranscript(
    cache, challengeForB, "RESPONDER", initiatorKp.nodeId, now,
  );

  // Create the genuine VerifiedTranscript — v7 API: wire bytes + proofA +
  // consumedChallenge + now. The freshnessVerifierNodeId is derived from
  // the ConsumedChallenge (no separate caller-supplied verifier identity).
  return createVerifiedTranscript({
    initiateBytes,
    acceptBytes,
    proofA,
    consumedChallenge,
    now,
  });
}

/**
 * Build a genuine BrandedCommittedRoute through the full proof-carrying
 * pipeline. Every hop is a genuine ValidatedHop (WeakSet-registered),
 * produced from a genuine AuthenticatedLink (which consumes a genuine
 * VerifiedTranscript + AuthenticatedNodeRecord).
 *
 * @param numHops  number of hops (last hop is INTERNET_GATEWAY, rest MESH_RELAY)
 * @param now      unix-seconds timestamp for the test
 */
export function makeGenuineBrandedRoute(
  numHops = 2,
  now = BRANDED_ROUTE_HELPER_NOW,
): BrandedRouteContext {
  const kps = Array.from({ length: numHops }, () => generateNodeKeypair());
  const initiator = generateNodeKeypair();

  const capabilities: NodeCapability[] = kps.map((_, i) =>
    i === kps.length - 1 ? "INTERNET_GATEWAY" : "MESH_RELAY",
  );

  const endpoints = kps.map((_, i) => `10.0.0.${i + 1}:7788`);

  // --- Per-hop: advertisement → verify → AuthenticatedNodeRecord ---
  const authNodes: AuthenticatedNodeRecord[] = [];
  const advHexes: string[] = [];
  for (let i = 0; i < kps.length; i++) {
    const kp = kps[i]!;
    const cap = capabilities[i]!;
    const adv = signAdvertisement({
      protocolVersion: 1,
      nodeId: kp.nodeId,
      signingPublicKey: kp.publicKey,
      capabilities: [cap],
      endpoints: [{ type: "tcp", address: `10.0.0.${i + 1}`, port: 7788 }],
      sequence: 1,
      timestamp: now,
      expiry: now + 3600,
      nonce: randomBytes(16),
    }, kp.secretKey);
    const v = verifyAdvertisement(adv, now);
    if (!v.ok) throw new Error(`advertisement verification failed for hop ${i}`);
    authNodes.push(createAuthenticatedNodeRecord(v.verified));
    advHexes.push(advertisementToHex(adv));
  }

  // --- Per-hop: 3-message handshake → VerifiedTranscript → AuthenticatedLink ---
  const verifiedTranscripts: VerifiedTranscript[] = [];
  const authenticatedLinks: AuthenticatedLink[] = [];
  // The initiator also needs an advertisement to participate in the handshake.
  const initiatorAdv = signAdvertisement({
    protocolVersion: 1,
    nodeId: initiator.nodeId,
    signingPublicKey: initiator.publicKey,
    capabilities: ["MESH_RELAY"],
    endpoints: [{ type: "tcp", address: "10.0.0.99", port: 7788 }],
    sequence: 1,
    timestamp: now,
    expiry: now + 3600,
    nonce: randomBytes(16),
  }, initiator.secretKey);
  const initiatorAdvHex = advertisementToHex(initiatorAdv);

  for (let i = 0; i < kps.length; i++) {
    // Run a genuine 3-message handshake: initiator ↔ hop node i.
    // The initiator is the "local" node; hop i is the "remote" node.
    const vt = runHandshake(
      initiator, kps[i]!,
      initiatorAdvHex, advHexes[i]!,
      now,
    );
    verifiedTranscripts.push(vt);

    const link = createAuthenticatedLink({
      localNodeId: initiator.nodeId,
      remoteNode: authNodes[i]!,
      verifiedTranscript: vt,
      establishedAt: now,
      expiresAt: now + 3600,
    });
    authenticatedLinks.push(link);
  }

  // --- Build the proposal hops (RouteHop[] for the proposal/acceptance) ---
  const hops: RouteHop[] = kps.map((kp, i) => ({
    nodeId: kp.nodeId,
    capability: capabilities[i]!,
    endpoint: endpoints[i]!,
    linkUp: true,
  }));

  const proposal: RouteProposal = {
    routeId: bytesToHex(randomBytes(32)),
    hops,
    requirementDigest: bytesToHex(randomBytes(32)),
    expiry: now + 3600,
    initiatorNodeId: initiator.nodeId,
    agreementDigest: bytesToHex(randomBytes(32)),
  };

  // --- Service agreements + public keys ---
  const serviceAgreements = new Map<number, ServiceAgreement>();
  const hopPublicKeys = new Map<string, Uint8Array>();
  for (let i = 0; i < kps.length; i++) {
    serviceAgreements.set(i, {
      nodeId: kps[i]!.nodeId,
      capability: capabilities[i]!,
      requirementDigest: proposal.requirementDigest,
      allocatedBandwidthBps: 1048576,
      expiry: proposal.expiry,
      policyVersion: 1,
    });
    hopPublicKeys.set(kps[i]!.nodeId, kps[i]!.publicKey);
  }

  // --- ValidatedHops (genuine, WeakSet-registered) ---
  // Per R-002-P1: consume genuine AuthenticatedLink (no caller-supplied linkUp boolean).
  // The serviceAgreementDigest carried in each ValidatedHop MUST match
  // the serviceDigest of the ServiceAgreement that the acceptance is
  // signed over — so the digests are consistent end-to-end.
  const validatedHops: ValidatedHop[] = [];
  for (let i = 0; i < kps.length; i++) {
    const saDigestHex = toHex(serviceDigest(serviceAgreements.get(i)!));
    validatedHops.push(
      createValidatedHop(
        authenticatedLinks[i]!,
        endpoints[i]!,
        capabilities[i]!,
        saDigestHex,
        now,
      ),
    );
  }

  // --- Acceptances + commitment ---
  const acceptances = kps.map((kp, i) =>
    signRouteAcceptance(
      proposal, i, hops[i]!,
      serviceAgreements.get(i)!,
      kp.nodeId, kp.secretKey, proposal.expiry,
    ),
  );

  const result = createRouteCommitment(
    proposal, acceptances, hopPublicKeys, serviceAgreements,
    initiator.secretKey, now,
  );
  if (!result.ok) throw new Error(`commitment failed: ${result.reason}`);

  // --- Branded route (genuine ValidatedHop[] passed explicitly — no cast) ---
  const branded = createBrandedCommittedRoute(result.commitment, validatedHops);

  return {
    branded,
    commitment: result.commitment,
    proposal,
    hops,
    validatedHops,
    authenticatedLinks,
    verifiedTranscripts,
    authNodes,
    kps,
    initiator,
    hopPublicKeys,
    serviceAgreements,
    capabilities,
    now,
  };
}
